export interface ModelData {
  name: string
  slug: string
  hallucinationRate: number
  factualConsistency: number
  answerRate: number
  avgSummaryLength: number
  trustScore: number
}

const rawData = [
  {
    name: "Google Gemini-2.0-Flash-001",
    hallucinationRate: 0.7,
    factualConsistency: 99.3,
    answerRate: 100.0,
    avgSummaryLength: 65.2,
  },
  {
    name: "Google Gemini-2.0-Pro-Exp",
    hallucinationRate: 0.8,
    factualConsistency: 99.2,
    answerRate: 99.7,
    avgSummaryLength: 61.5,
  },
  {
    name: "OpenAI o3-mini-high",
    hallucinationRate: 0.8,
    factualConsistency: 99.2,
    answerRate: 100.0,
    avgSummaryLength: 79.5,
  },
  {
    name: "Vectara Mockingbird-2-Echo",
    hallucinationRate: 0.9,
    factualConsistency: 99.1,
    answerRate: 100.0,
    avgSummaryLength: 74.0,
  },
  {
    name: "Moonshot AI Kimi-K2-Instruct",
    hallucinationRate: 1.1,
    factualConsistency: 98.9,
    answerRate: 89.5,
    avgSummaryLength: 73.2,
  },
  {
    name: "Google Gemini-2.5-Pro-Exp-0325",
    hallucinationRate: 1.1,
    factualConsistency: 98.9,
    answerRate: 95.1,
    avgSummaryLength: 72.9,
  },
  {
    name: "Google Gemini-2.0-Flash-Lite-Preview",
    hallucinationRate: 1.2,
    factualConsistency: 98.8,
    answerRate: 99.5,
    avgSummaryLength: 60.9,
  },
  {
    name: "OpenAI GPT-4.5-Preview",
    hallucinationRate: 1.2,
    factualConsistency: 98.8,
    answerRate: 100.0,
    avgSummaryLength: 77.0,
  },
  {
    name: "Zhipu AI GLM-4-9B-Chat",
    hallucinationRate: 1.3,
    factualConsistency: 98.7,
    answerRate: 100.0,
    avgSummaryLength: 58.1,
  },
  {
    name: "Google Gemini-2.0-Flash-Exp",
    hallucinationRate: 1.3,
    factualConsistency: 98.7,
    answerRate: 99.9,
    avgSummaryLength: 60.0,
  },
  {
    name: "Google Gemini-2.5-Flash-Preview",
    hallucinationRate: 1.3,
    factualConsistency: 98.7,
    answerRate: 91.2,
    avgSummaryLength: 71.1,
  },
  {
    name: "OpenAI-o1-mini",
    hallucinationRate: 1.4,
    factualConsistency: 98.6,
    answerRate: 100.0,
    avgSummaryLength: 78.3,
  },
  {
    name: "OpenAI GPT-4o",
    hallucinationRate: 1.5,
    factualConsistency: 98.5,
    answerRate: 100.0,
    avgSummaryLength: 77.8,
  },
  {
    name: "Amazon Nova-Micro-V1",
    hallucinationRate: 1.6,
    factualConsistency: 98.4,
    answerRate: 100.0,
    avgSummaryLength: 90.0,
  },
  {
    name: "OpenAI GPT-4o-mini",
    hallucinationRate: 1.7,
    factualConsistency: 98.3,
    answerRate: 100.0,
    avgSummaryLength: 76.3,
  },
  {
    name: "OpenAI GPT-4-Turbo",
    hallucinationRate: 1.7,
    factualConsistency: 98.3,
    answerRate: 100.0,
    avgSummaryLength: 86.2,
  },
  {
    name: "Google Gemini-2.0-Flash-Thinking-Exp",
    hallucinationRate: 1.8,
    factualConsistency: 98.2,
    answerRate: 99.3,
    avgSummaryLength: 73.2,
  },
  {
    name: "Amazon Nova-Lite-V1",
    hallucinationRate: 1.8,
    factualConsistency: 98.2,
    answerRate: 99.9,
    avgSummaryLength: 80.7,
  },
  { name: "OpenAI GPT-4", hallucinationRate: 1.8, factualConsistency: 98.2, answerRate: 100.0, avgSummaryLength: 81.1 },
  {
    name: "Amazon Nova-Pro-V1",
    hallucinationRate: 1.8,
    factualConsistency: 98.2,
    answerRate: 100.0,
    avgSummaryLength: 85.5,
  },
  {
    name: "OpenAI GPT-3.5-Turbo",
    hallucinationRate: 1.9,
    factualConsistency: 98.1,
    answerRate: 99.6,
    avgSummaryLength: 84.1,
  },
  { name: "XAI Grok-2", hallucinationRate: 1.9, factualConsistency: 98.1, answerRate: 100.0, avgSummaryLength: 86.5 },
  {
    name: "OpenAI GPT-4.1-nano",
    hallucinationRate: 2.0,
    factualConsistency: 98.0,
    answerRate: 100.0,
    avgSummaryLength: 70.2,
  },
  {
    name: "OpenAI GPT-4.1",
    hallucinationRate: 2.0,
    factualConsistency: 98.0,
    answerRate: 100.0,
    avgSummaryLength: 71.9,
  },
  {
    name: "XAI Grok-3-Beta",
    hallucinationRate: 2.1,
    factualConsistency: 97.8,
    answerRate: 100.0,
    avgSummaryLength: 97.7,
  },
  {
    name: "OpenAI GPT-4.1-mini",
    hallucinationRate: 2.2,
    factualConsistency: 97.8,
    answerRate: 100.0,
    avgSummaryLength: 79.6,
  },
  { name: "Qwen3-14B", hallucinationRate: 2.2, factualConsistency: 97.8, answerRate: 100.0, avgSummaryLength: 82.4 },
  {
    name: "AI21 Jamba-1.6-Large",
    hallucinationRate: 2.3,
    factualConsistency: 97.7,
    answerRate: 99.9,
    avgSummaryLength: 85.6,
  },
  {
    name: "OpenAI o1-Pro",
    hallucinationRate: 2.4,
    factualConsistency: 97.6,
    answerRate: 100.0,
    avgSummaryLength: 81.0,
  },
  { name: "OpenAI o1", hallucinationRate: 2.4, factualConsistency: 97.6, answerRate: 99.9, avgSummaryLength: 73.0 },
  {
    name: "DeepSeek-V2.5",
    hallucinationRate: 2.4,
    factualConsistency: 97.6,
    answerRate: 100.0,
    avgSummaryLength: 83.2,
  },
  {
    name: "Microsoft Orca-2-13b",
    hallucinationRate: 2.5,
    factualConsistency: 97.5,
    answerRate: 100.0,
    avgSummaryLength: 66.2,
  },
  {
    name: "Microsoft Phi-3.5-MoE-instruct",
    hallucinationRate: 2.5,
    factualConsistency: 97.5,
    answerRate: 96.3,
    avgSummaryLength: 69.7,
  },
  {
    name: "Google Gemini-2.5-Pro-Preview-06-05",
    hallucinationRate: 2.6,
    factualConsistency: 97.4,
    answerRate: 99.6,
    avgSummaryLength: 73.1,
  },
  {
    name: "Intel Neural-Chat-7B-v3-3",
    hallucinationRate: 2.6,
    factualConsistency: 97.4,
    answerRate: 100.0,
    avgSummaryLength: 60.7,
  },
  { name: "Qwen3-4B", hallucinationRate: 2.7, factualConsistency: 97.3, answerRate: 100.0, avgSummaryLength: 87.7 },
  {
    name: "Google Gemma-3-12B-Instruct",
    hallucinationRate: 2.8,
    factualConsistency: 97.2,
    answerRate: 100.0,
    avgSummaryLength: 69.6,
  },
  {
    name: "Qwen2.5-7B-Instruct",
    hallucinationRate: 2.8,
    factualConsistency: 97.2,
    answerRate: 100.0,
    avgSummaryLength: 71.0,
  },
  { name: "Qwen3-32B", hallucinationRate: 2.8, factualConsistency: 97.2, answerRate: 100.0, avgSummaryLength: 82.4 },
  {
    name: "Google Gemini-2.5-Flash-Lite",
    hallucinationRate: 2.9,
    factualConsistency: 97.1,
    answerRate: 99.7,
    avgSummaryLength: 78.4,
  },
  {
    name: "AI21 Jamba-1.5-Mini",
    hallucinationRate: 2.9,
    factualConsistency: 97.1,
    answerRate: 95.6,
    avgSummaryLength: 74.5,
  },
  {
    name: "XAI Grok-2-Vision",
    hallucinationRate: 2.9,
    factualConsistency: 97.1,
    answerRate: 100.0,
    avgSummaryLength: 79.8,
  },
  { name: "Qwen2.5-Max", hallucinationRate: 2.9, factualConsistency: 97.1, answerRate: 88.8, avgSummaryLength: 90.4 },
  {
    name: "Google Gemma-3-27B-Instruct",
    hallucinationRate: 3.0,
    factualConsistency: 97.0,
    answerRate: 100.0,
    avgSummaryLength: 62.5,
  },
  {
    name: "Qwen2.5-32B-Instruct",
    hallucinationRate: 3.0,
    factualConsistency: 97.0,
    answerRate: 100.0,
    avgSummaryLength: 67.9,
  },
  {
    name: "Snowflake-Arctic-Instruct",
    hallucinationRate: 3.0,
    factualConsistency: 97.0,
    answerRate: 100.0,
    avgSummaryLength: 68.7,
  },
  { name: "Qwen3-8B", hallucinationRate: 3.0, factualConsistency: 97.0, answerRate: 100.0, avgSummaryLength: 78.2 },
  {
    name: "Microsoft Phi-3-mini-128k-instruct",
    hallucinationRate: 3.1,
    factualConsistency: 96.9,
    answerRate: 100.0,
    avgSummaryLength: 60.1,
  },
  {
    name: "Mistral Small3",
    hallucinationRate: 3.1,
    factualConsistency: 96.9,
    answerRate: 100.0,
    avgSummaryLength: 74.9,
  },
  {
    name: "XAI Grok-3-Mini-Beta",
    hallucinationRate: 3.3,
    factualConsistency: 96.7,
    answerRate: 100.0,
    avgSummaryLength: 90.2,
  },
  {
    name: "OpenAI o1-preview",
    hallucinationRate: 3.3,
    factualConsistency: 96.7,
    answerRate: 100.0,
    avgSummaryLength: 119.3,
  },
  {
    name: "Google Gemini-1.5-Flash-002",
    hallucinationRate: 3.4,
    factualConsistency: 96.6,
    answerRate: 99.9,
    avgSummaryLength: 59.4,
  },
  {
    name: "Microsoft Phi-4-mini-instruct",
    hallucinationRate: 3.4,
    factualConsistency: 96.6,
    answerRate: 100.0,
    avgSummaryLength: 69.7,
  },
  {
    name: "Google Gemma-3-4B-Instruct",
    hallucinationRate: 3.7,
    factualConsistency: 96.3,
    answerRate: 100.0,
    avgSummaryLength: 63.7,
  },
  { name: "Qwen3-0.6B", hallucinationRate: 3.7, factualConsistency: 96.3, answerRate: 100.0, avgSummaryLength: 65.3 },
  {
    name: "01-AI Yi-1.5-34B-Chat",
    hallucinationRate: 3.7,
    factualConsistency: 96.3,
    answerRate: 100.0,
    avgSummaryLength: 83.7,
  },
  {
    name: "Llama-3.1-405B-Instruct",
    hallucinationRate: 3.9,
    factualConsistency: 96.1,
    answerRate: 99.6,
    avgSummaryLength: 85.7,
  },
  { name: "DeepSeek-V3", hallucinationRate: 3.9, factualConsistency: 96.1, answerRate: 100.0, avgSummaryLength: 88.2 },
  {
    name: "Microsoft Phi-3-mini-4k-instruct",
    hallucinationRate: 4.0,
    factualConsistency: 96.0,
    answerRate: 100.0,
    avgSummaryLength: 86.8,
  },
  {
    name: "Llama-3.3-70B-Instruct",
    hallucinationRate: 4.0,
    factualConsistency: 96.0,
    answerRate: 100.0,
    avgSummaryLength: 85.3,
  },
  {
    name: "InternLM3-8B-Instruct",
    hallucinationRate: 4.0,
    factualConsistency: 96.0,
    answerRate: 100.0,
    avgSummaryLength: 97.5,
  },
  {
    name: "Microsoft Phi-3.5-mini-instruct",
    hallucinationRate: 4.1,
    factualConsistency: 95.9,
    answerRate: 100.0,
    avgSummaryLength: 75.0,
  },
  {
    name: "Mistral-Large2",
    hallucinationRate: 4.1,
    factualConsistency: 95.9,
    answerRate: 100.0,
    avgSummaryLength: 77.4,
  },
  {
    name: "Llama-3-70B-Chat-hf",
    hallucinationRate: 4.1,
    factualConsistency: 95.9,
    answerRate: 99.2,
    avgSummaryLength: 68.5,
  },
  {
    name: "Qwen2-VL-7B-Instruct",
    hallucinationRate: 4.2,
    factualConsistency: 95.8,
    answerRate: 100.0,
    avgSummaryLength: 73.9,
  },
  {
    name: "Qwen2.5-14B-Instruct",
    hallucinationRate: 4.2,
    factualConsistency: 95.8,
    answerRate: 100.0,
    avgSummaryLength: 74.8,
  },
  {
    name: "Qwen2.5-72B-Instruct",
    hallucinationRate: 4.3,
    factualConsistency: 95.7,
    answerRate: 100.0,
    avgSummaryLength: 80.0,
  },
  {
    name: "Llama-3.2-90B-Vision-Instruct",
    hallucinationRate: 4.3,
    factualConsistency: 95.7,
    answerRate: 100.0,
    avgSummaryLength: 79.8,
  },
  { name: "Qwen3-1.7B", hallucinationRate: 4.4, factualConsistency: 95.6, answerRate: 100.0, avgSummaryLength: 69.0 },
  {
    name: "Claude-3.7-Sonnet",
    hallucinationRate: 4.4,
    factualConsistency: 95.6,
    answerRate: 100.0,
    avgSummaryLength: 97.8,
  },
  {
    name: "Claude-4-Sonnet",
    hallucinationRate: 4.5,
    factualConsistency: 95.5,
    answerRate: 100.0,
    avgSummaryLength: 116.0,
  },
  {
    name: "Claude-3.7-Sonnet-Think",
    hallucinationRate: 4.5,
    factualConsistency: 95.5,
    answerRate: 99.8,
    avgSummaryLength: 99.9,
  },
  {
    name: "Cohere Command-A",
    hallucinationRate: 4.5,
    factualConsistency: 95.5,
    answerRate: 100.0,
    avgSummaryLength: 77.3,
  },
  {
    name: "OpenAI o4-mini",
    hallucinationRate: 4.6,
    factualConsistency: 95.4,
    answerRate: 100.0,
    avgSummaryLength: 82.0,
  },
  {
    name: "AI21 Jamba-1.6-Mini",
    hallucinationRate: 4.6,
    factualConsistency: 95.4,
    answerRate: 100.0,
    avgSummaryLength: 82.3,
  },
  {
    name: "Meta Llama-4-Maverick",
    hallucinationRate: 4.6,
    factualConsistency: 95.4,
    answerRate: 100.0,
    avgSummaryLength: 84.8,
  },
  { name: "XAI Grok", hallucinationRate: 4.6, factualConsistency: 95.4, answerRate: 100.0, avgSummaryLength: 91.0 },
  {
    name: "Anthropic Claude-3-5-sonnet",
    hallucinationRate: 4.6,
    factualConsistency: 95.4,
    answerRate: 100.0,
    avgSummaryLength: 95.9,
  },
  {
    name: "Meta Llama-4-Scout",
    hallucinationRate: 4.7,
    factualConsistency: 95.3,
    answerRate: 100.0,
    avgSummaryLength: 80.7,
  },
  {
    name: "Qwen2-72B-Instruct",
    hallucinationRate: 4.7,
    factualConsistency: 95.3,
    answerRate: 100.0,
    avgSummaryLength: 100.1,
  },
  {
    name: "Microsoft Phi-4",
    hallucinationRate: 4.7,
    factualConsistency: 95.3,
    answerRate: 100.0,
    avgSummaryLength: 100.3,
  },
  {
    name: "Mixtral-8x22B-Instruct-v0.1",
    hallucinationRate: 4.7,
    factualConsistency: 95.3,
    answerRate: 99.9,
    avgSummaryLength: 92.0,
  },
  {
    name: "Claude-4-Opus",
    hallucinationRate: 4.8,
    factualConsistency: 95.2,
    answerRate: 100.0,
    avgSummaryLength: 110.0,
  },
  {
    name: "XAI Grok-4-0709",
    hallucinationRate: 4.8,
    factualConsistency: 95.2,
    answerRate: 99.8,
    avgSummaryLength: 100.6,
  },
  {
    name: "Anthropic Claude-3-5-haiku",
    hallucinationRate: 4.9,
    factualConsistency: 95.1,
    answerRate: 100.0,
    avgSummaryLength: 92.9,
  },
  {
    name: "01-AI Yi-1.5-9B-Chat",
    hallucinationRate: 4.9,
    factualConsistency: 95.1,
    answerRate: 100.0,
    avgSummaryLength: 85.7,
  },
  {
    name: "Cohere Command-R",
    hallucinationRate: 4.9,
    factualConsistency: 95.1,
    answerRate: 100.0,
    avgSummaryLength: 68.7,
  },
  {
    name: "Llama-3.1-70B-Instruct",
    hallucinationRate: 5.0,
    factualConsistency: 95.0,
    answerRate: 100.0,
    avgSummaryLength: 79.6,
  },
  {
    name: "OpenAI o4-mini-high",
    hallucinationRate: 5.1,
    factualConsistency: 94.9,
    answerRate: 98.2,
    avgSummaryLength: 79.2,
  },
  {
    name: "Google Gemma-3-1B-Instruct",
    hallucinationRate: 5.3,
    factualConsistency: 94.7,
    answerRate: 99.9,
    avgSummaryLength: 57.9,
  },
  {
    name: "Llama-3.1-8B-Instruct",
    hallucinationRate: 5.4,
    factualConsistency: 94.6,
    answerRate: 100.0,
    avgSummaryLength: 71.0,
  },
  {
    name: "Cohere Command-R-Plus",
    hallucinationRate: 5.4,
    factualConsistency: 94.6,
    answerRate: 100.0,
    avgSummaryLength: 68.4,
  },
  {
    name: "Llama-3.2-11B-Vision-Instruct",
    hallucinationRate: 5.5,
    factualConsistency: 94.5,
    answerRate: 100.0,
    avgSummaryLength: 67.3,
  },
  {
    name: "TNGTech DeepSeek-TNG-R1T2-Chimera",
    hallucinationRate: 5.5,
    factualConsistency: 94.5,
    answerRate: 99.6,
    avgSummaryLength: 78.6,
  },
  {
    name: "Mistral-Small-3.1-24B-Instruct",
    hallucinationRate: 5.6,
    factualConsistency: 94.4,
    answerRate: 100.0,
    avgSummaryLength: 73.1,
  },
  {
    name: "Llama-2-70B-Chat-hf",
    hallucinationRate: 5.9,
    factualConsistency: 94.1,
    answerRate: 99.9,
    avgSummaryLength: 84.9,
  },
  {
    name: "IBM Granite-3.0-8B-Instruct",
    hallucinationRate: 6.5,
    factualConsistency: 93.5,
    answerRate: 100.0,
    avgSummaryLength: 74.2,
  },
  {
    name: "Google Gemini-1.5-Pro-002",
    hallucinationRate: 6.6,
    factualConsistency: 93.7,
    answerRate: 99.9,
    avgSummaryLength: 62.0,
  },
  {
    name: "Google Gemini-1.5-Flash",
    hallucinationRate: 6.6,
    factualConsistency: 93.4,
    answerRate: 99.9,
    avgSummaryLength: 63.3,
  },
  {
    name: "Mistral-Pixtral",
    hallucinationRate: 6.6,
    factualConsistency: 93.4,
    answerRate: 100.0,
    avgSummaryLength: 76.4,
  },
  {
    name: "Microsoft phi-2",
    hallucinationRate: 6.7,
    factualConsistency: 93.3,
    answerRate: 91.5,
    avgSummaryLength: 80.8,
  },
  {
    name: "OpenAI o4-mini-low",
    hallucinationRate: 6.8,
    factualConsistency: 93.2,
    answerRate: 99.8,
    avgSummaryLength: 81.6,
  },
  { name: "OpenAI o3", hallucinationRate: 6.8, factualConsistency: 93.2, answerRate: 100.0, avgSummaryLength: 77.7 },
  {
    name: "Google Gemma-2-2B-it",
    hallucinationRate: 7.0,
    factualConsistency: 93.0,
    answerRate: 100.0,
    avgSummaryLength: 62.2,
  },
  {
    name: "Qwen2.5-3B-Instruct",
    hallucinationRate: 7.0,
    factualConsistency: 93.0,
    answerRate: 100.0,
    avgSummaryLength: 70.4,
  },
  {
    name: "Llama-3-8B-Chat-hf",
    hallucinationRate: 7.4,
    factualConsistency: 92.6,
    answerRate: 99.8,
    avgSummaryLength: 79.7,
  },
  {
    name: "Mistral-Ministral-8B",
    hallucinationRate: 7.5,
    factualConsistency: 92.5,
    answerRate: 100.0,
    avgSummaryLength: 62.7,
  },
  {
    name: "Google Gemini-Pro",
    hallucinationRate: 7.7,
    factualConsistency: 92.3,
    answerRate: 98.4,
    avgSummaryLength: 89.5,
  },
  {
    name: "DeepSeek-R1-0528",
    hallucinationRate: 7.7,
    factualConsistency: 92.3,
    answerRate: 100.0,
    avgSummaryLength: 138.9,
  },
  {
    name: "01-AI Yi-1.5-6B-Chat",
    hallucinationRate: 7.9,
    factualConsistency: 92.1,
    answerRate: 100.0,
    avgSummaryLength: 98.9,
  },
  {
    name: "Llama-3.2-3B-Instruct",
    hallucinationRate: 7.9,
    factualConsistency: 92.1,
    answerRate: 100.0,
    avgSummaryLength: 72.2,
  },
  {
    name: "DeepSeek-V3-0324",
    hallucinationRate: 8.0,
    factualConsistency: 92.0,
    answerRate: 100.0,
    avgSummaryLength: 78.9,
  },
  {
    name: "Mistral-Ministral-3B",
    hallucinationRate: 8.3,
    factualConsistency: 91.7,
    answerRate: 100.0,
    avgSummaryLength: 73.2,
  },
  {
    name: "databricks dbrx-instruct",
    hallucinationRate: 8.3,
    factualConsistency: 91.7,
    answerRate: 100.0,
    avgSummaryLength: 85.9,
  },
  {
    name: "Qwen2-VL-2B-Instruct",
    hallucinationRate: 8.3,
    factualConsistency: 91.7,
    answerRate: 100.0,
    avgSummaryLength: 81.8,
  },
  {
    name: "Cohere Aya Expanse 32B",
    hallucinationRate: 8.5,
    factualConsistency: 91.5,
    answerRate: 99.9,
    avgSummaryLength: 81.9,
  },
  {
    name: "IBM Granite-3.1-8B-Instruct",
    hallucinationRate: 8.6,
    factualConsistency: 91.4,
    answerRate: 100.0,
    avgSummaryLength: 107.4,
  },
  {
    name: "Mistral-Small2",
    hallucinationRate: 8.6,
    factualConsistency: 91.4,
    answerRate: 100.0,
    avgSummaryLength: 74.2,
  },
  {
    name: "IBM Granite-3.2-8B-Instruct",
    hallucinationRate: 8.7,
    factualConsistency: 91.3,
    answerRate: 100.0,
    avgSummaryLength: 120.1,
  },
  {
    name: "IBM Granite-3.0-2B-Instruct",
    hallucinationRate: 8.8,
    factualConsistency: 91.2,
    answerRate: 100.0,
    avgSummaryLength: 81.6,
  },
  {
    name: "Mistral-7B-Instruct-v0.3",
    hallucinationRate: 9.5,
    factualConsistency: 90.5,
    answerRate: 100.0,
    avgSummaryLength: 98.4,
  },
  {
    name: "Google Gemini-1.5-Pro",
    hallucinationRate: 9.1,
    factualConsistency: 90.9,
    answerRate: 99.8,
    avgSummaryLength: 61.6,
  },
  {
    name: "Anthropic Claude-3-opus",
    hallucinationRate: 10.1,
    factualConsistency: 89.9,
    answerRate: 95.5,
    avgSummaryLength: 92.1,
  },
  {
    name: "Google Gemma-2-9B-it",
    hallucinationRate: 10.1,
    factualConsistency: 89.9,
    answerRate: 100.0,
    avgSummaryLength: 70.2,
  },
  {
    name: "Llama-2-13B-Chat-hf",
    hallucinationRate: 10.5,
    factualConsistency: 89.5,
    answerRate: 99.8,
    avgSummaryLength: 82.1,
  },
  {
    name: "AllenAI-OLMo-2-13B-Instruct",
    hallucinationRate: 10.8,
    factualConsistency: 89.2,
    answerRate: 100.0,
    avgSummaryLength: 82.0,
  },
  {
    name: "AllenAI-OLMo-2-7B-Instruct",
    hallucinationRate: 11.1,
    factualConsistency: 88.9,
    answerRate: 100.0,
    avgSummaryLength: 112.6,
  },
  {
    name: "Mistral-Nemo-Instruct",
    hallucinationRate: 11.2,
    factualConsistency: 88.8,
    answerRate: 100.0,
    avgSummaryLength: 69.9,
  },
  {
    name: "Llama-2-7B-Chat-hf",
    hallucinationRate: 11.3,
    factualConsistency: 88.7,
    answerRate: 99.6,
    avgSummaryLength: 119.9,
  },
  {
    name: "Microsoft WizardLM-2-8x22B",
    hallucinationRate: 11.7,
    factualConsistency: 88.3,
    answerRate: 99.9,
    avgSummaryLength: 140.8,
  },
  {
    name: "Cohere Aya Expanse 8B",
    hallucinationRate: 12.2,
    factualConsistency: 87.8,
    answerRate: 99.9,
    avgSummaryLength: 83.9,
  },
  {
    name: "Amazon Titan-Express",
    hallucinationRate: 13.5,
    factualConsistency: 86.5,
    answerRate: 99.5,
    avgSummaryLength: 98.4,
  },
  {
    name: "Google PaLM-2",
    hallucinationRate: 14.1,
    factualConsistency: 85.9,
    answerRate: 99.8,
    avgSummaryLength: 86.6,
  },
  { name: "DeepSeek-R1", hallucinationRate: 14.3, factualConsistency: 85.7, answerRate: 100.0, avgSummaryLength: 77.1 },
  {
    name: "Google Gemma-7B-it",
    hallucinationRate: 14.8,
    factualConsistency: 85.2,
    answerRate: 100.0,
    avgSummaryLength: 113.0,
  },
  {
    name: "IBM Granite-3.1-2B-Instruct",
    hallucinationRate: 15.7,
    factualConsistency: 84.3,
    answerRate: 100.0,
    avgSummaryLength: 107.7,
  },
  {
    name: "Qwen2.5-1.5B-Instruct",
    hallucinationRate: 15.8,
    factualConsistency: 84.2,
    answerRate: 100.0,
    avgSummaryLength: 70.7,
  },
  {
    name: "Qwen-QwQ-32B-Preview",
    hallucinationRate: 16.1,
    factualConsistency: 83.9,
    answerRate: 100.0,
    avgSummaryLength: 201.5,
  },
  {
    name: "Anthropic Claude-3-sonnet",
    hallucinationRate: 16.3,
    factualConsistency: 83.7,
    answerRate: 100.0,
    avgSummaryLength: 108.5,
  },
  {
    name: "IBM Granite-3.2-2B-Instruct",
    hallucinationRate: 16.5,
    factualConsistency: 83.5,
    answerRate: 100.0,
    avgSummaryLength: 117.7,
  },
  {
    name: "Google Gemma-1.1-7B-it",
    hallucinationRate: 17.0,
    factualConsistency: 83.0,
    answerRate: 100.0,
    avgSummaryLength: 64.3,
  },
  {
    name: "Anthropic Claude-2",
    hallucinationRate: 17.4,
    factualConsistency: 82.6,
    answerRate: 99.3,
    avgSummaryLength: 87.5,
  },
  {
    name: "Google Flan-T5-large",
    hallucinationRate: 18.3,
    factualConsistency: 81.7,
    answerRate: 99.3,
    avgSummaryLength: 20.9,
  },
  {
    name: "Mixtral-8x7B-Instruct-v0.1",
    hallucinationRate: 20.1,
    factualConsistency: 79.9,
    answerRate: 99.9,
    avgSummaryLength: 90.7,
  },
  {
    name: "Llama-3.2-1B-Instruct",
    hallucinationRate: 20.7,
    factualConsistency: 79.3,
    answerRate: 100.0,
    avgSummaryLength: 71.5,
  },
  {
    name: "Apple OpenELM-3B-Instruct",
    hallucinationRate: 24.8,
    factualConsistency: 75.2,
    answerRate: 99.3,
    avgSummaryLength: 47.2,
  },
  {
    name: "Qwen2.5-0.5B-Instruct",
    hallucinationRate: 25.2,
    factualConsistency: 74.8,
    answerRate: 100.0,
    avgSummaryLength: 72.6,
  },
  {
    name: "Google Gemma-1.1-2B-it",
    hallucinationRate: 27.8,
    factualConsistency: 72.2,
    answerRate: 100.0,
    avgSummaryLength: 66.8,
  },
  {
    name: "TII falcon-7B-instruct",
    hallucinationRate: 29.9,
    factualConsistency: 70.1,
    answerRate: 90.0,
    avgSummaryLength: 75.5,
  },
]

function createSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
}

export const models: ModelData[] = rawData
  .map((model) => ({
    ...model,
    slug: createSlug(model.name),
    trustScore: model.factualConsistency - model.hallucinationRate,
  }))
  .sort((a, b) => b.trustScore - a.trustScore)

export function getModelBySlug(slug: string): ModelData | undefined {
  return models.find((model) => model.slug === slug)
}

export function getTrustScoreBadge(score: number): { color: string; label: string } {
  if (score > 90) {
    return { color: "bg-green-100 text-green-800", label: "Excellent" }
  } else if (score >= 70) {
    return { color: "bg-yellow-100 text-yellow-800", label: "Good" }
  } else {
    return { color: "bg-red-100 text-red-800", label: "Poor" }
  }
}
